title: Duc NX's blog
email: me@ducnx.com
description: > # this means to ignore newlines until "baseurl:"
  My personal blog, about things I learn.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ducnx.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: xuanduc987
github_username:  xuanduc987

# Build settings
permalink:   /:categories/:title/
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
